# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f0782d34b6d43ca82bc93fc84621a4b71768a759d6560bbb3befad9ff0c61998399b16e332fdb82f350bad5d61b75d1e6a0f7a0fcb35b136e0b511dbfb20c49

test:
  secret_key_base: 185ba3c59760cce08d8cd3fc9bb84d881d77e0a3bc4404721d433285f6e1a636baa90658077dd5a23aa64d8957895e921e80750c5903e95641266d96ccc63ceb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
